#!/bin/bash
echo ""
echo "installing ..."
echo ""
termux-setup-storage & sleep 5 &>/dev/null
pkg update -y

echo ""
echo " Installing x11-repo..."
echo ""

pkg install x11-repo -y 

echo ""
echo ""
echo "installing pulseaudio,termux-x11,proot packages"


if pkg install pulseaudio wget xkeyboard-config proot -y
then
  echo "Aditional packages is installed"
else
  echo "Aditional packages installation is failed"
fi

echo " Downloading and installing Qemu"
cd ~
wget https://github.com/gamextra4u/FEXDroid/raw/refs/heads/main/qemu-x86_64
chmod +x qemu-x86_64
mv ~/qemu-x86_64 $PREFIX/bin

if pkg install termux-x11-nightly -y & sleep 10
then
  echo "termux-x11 is installed"
else
  echo "Termux-x11 is not Installed"
fi
sleep 1
clear

echo ""

echo ""

  cd ~
ROOTFS_DIR="FEXDroid"
ROOTFS_LINK="https://github.com/gamextra4u/FEXDroid/releases/download/v1.0/FEXDroid.tar.gz"  
ROOTFS_ARCHIVE="FEXDroid.tar.gz"

# Check if FEXDroid folder already exists
if [ -d "$ROOTFS_DIR" ]; then
    echo "[✔] $ROOTFS_DIR already exists. Skipping download."
else
    echo "[⏬] Downloading Ubuntu rootfs..."
    wget -q --show-progress "$ROOTFS_LINK"  || { echo "[✖] Download failed!"; exit 1; }

    echo "[📦] Extracting rootfs to $ROOTFS_DIR..."
   tar -xzvf FEXDroid.tar.gz &>/dev/null  || { echo "[✖] Extraction failed!"; exit 1; }
    rm "$ROOTFS_ARCHIVE"
    echo "[✅] Rootfs ready in $ROOTFS_DIR"
fi

  echo ""
echo " Rootfs installed"
  
  sleep 3

  echo " Downloading FEXDroid launch script..."
  
  cd ~
  wget https://raw.githubusercontent.com/gamextra4u/FEXDroid/refs/heads/gamextra4u-patch-1/fexdroid
  chmod +x fexdroid
  mv fexdroid $PREFIX/bin/fexdroid
  
  echo ""
echo " Scripts installed"
echo ""

echo ""
echo "Replacing Vulkan freedreno library..."

VULKAN_URL="https://github.com/gamextra4u/FEXDroid/raw/refs/heads/main/libvulkan_freedreno.so"
DEST_DIR=~/FEXDroid/ubuntu-fs/lib/aarch64-linux-gnu
DEST_FILE="$DEST_DIR/libvulkan_freedreno.so"


# Remove old file if exists
rm -f "$DEST_FILE"

# Download new file with SAME NAME
wget -q --show-progress "$VULKAN_URL" -O "$DEST_FILE" || { 
    echo "[✖] Vulkan freedreno library download failed!"; 
    exit 1; 
}

chmod 644 "$DEST_FILE"
echo "[✅] Vulkan freedreno library replaced successfully."
  clear
echo ""
echo " Installation finished. To start FEXDroid type "fexdroid" "
  
